apiVersion: 1.0
type: demo
name: product_tabs
label: Product Tabs
description: All tabs render dynamic ui

includes:
  - path: /tabs/car
  - path: /tabs/food

tabs:
  - name: car
    label: Car
    doc: doc_car
    
  - name: food
    label: Food
    doc: doc_food